// ============================================================
//  VANGUARD MD — commands/imagine.js
//  AI Image Generator using EliteProTech API
// ============================================================

const axios = require('axios')

module.exports = async (ctx) => {
  const { sock, jid, msg, args, reply } = ctx

  const prompt = args.join(' ').trim()

  if (!prompt) {
    return reply(
      '🖼️ *IMAGINE*\n\n' +
      'Usage: .imagine <your prompt>\n' +
      'Example: .imagine a cyberpunk samurai riding a dragon\n\n' +
      'Powered by EliteProTech '
    )
  }

  await reply('⏳ Generating image...')

  try {
    const response = await axios.get(`https://eliteprotech-apis.zone.id/e.id/imagine?prompt=${encodeURIComponent(prompt)}`, {
      timeout: 30000
    })

    const imageUrl = response.data?.image || response.data?.url || response.data?.result

    if (!imageUrl) {
      return reply('❌ Failed to generate image. API returned no image.')
    }

    await sock.sendMessage(jid, {
      image: { url: imageUrl },
      caption: `🖼️ *Generated by Vanguard MD*\n\nPrompt: ${prompt}`
    }, { quoted: msg })

  } catch (error) {
    console.error('Imagine error:', error.message)
    await reply('❌ Failed to generate image.\nThe API might be down or slow.')
  }
}
